#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}
#+LaTex_HEADER: \newcommand*{\shift}{\ensuremath{\operatorname{q}}}
# #+LaTex_HEADER: \renewcommand*{\vec}[1]{\ensuremath{ \mathbf{#1}}}
#+LaTex_HEADER: \newcommand*{\vecref}[2]{\ensuremath{^#2 \vec{#1}}}
#+LaTex_HEADER: \newcommand*{\pref}[2]{\ensuremath{^#2{#1}}}
#+LaTex_HEADER: \newcommand*{\refsys}[1]{\ensuremath{\{#1\}}}
#+LaTex_HEADER:\newcommand*{\refframe}[4]{%
#+LaTex_HEADER: \draw[->, thick, #4] (0,0) to (#1, 0) node[right]{#2};
#+LaTex_HEADER: \draw[->, thick, #4] (0,0) to (0, #1) node[above]{#3};} 


#+title: Cinemática - Representación de posición y orientación
# #+date: 2021-06-28

* What do I want the students to understand?			   :noexport:
  - Points, vectors, rigid body transformations in 2D and 3D


* Which activities will the students do?			   :noexport:
  1. Writing code for creating a rotation matrix in two dimensions.
  2. 

* Intro
** Definiciones

\begin{center}
\includegraphics[height=0.5\textheight]{../figures/Corke-fig2.1.a.png}

\footnotesize Peter Corke \emph{Robotics, vision and control}
\end{center}


** Uso de sistemas de referencia en robótica

\begin{center}
\includegraphics[height=0.5\textheight]{../figures/Corke-fig2.4.png}

\footnotesize Peter Corke \emph{Robotics, vision and control}
\end{center}

* Pose en 2D

# The next two slides on the whiteboard instead.
** Pose en 2D                                                      :noexport:

\begin{center}
\includegraphics[height=0.5\textheight]{../figures/Corke-fig2.6.png}

\footnotesize Peter Corke \emph{Robotics, vision and control}
\end{center}

** Pose en 2D                                                      :noexport:

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.2
:END:

\begin{center}
\includegraphics[height=0.3\textheight]{../figures/Corke-fig2.6.png}

\footnotesize Peter Corke \emph{Robotics, vision and control}
\end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.8
:END:

\small 

El vector $\vec{x_B}$ en sistema \refsys{A}: \[ \vec{x_B} = \cos\theta \vec{x_A} +\sin\theta\vec{y_A} =
\begin{bmatrix}\vec{x_A} & \vec{y_A} \end{bmatrix} \begin{bmatrix} \cos\theta\\\sin\theta \end{bmatrix}\]

#+BEAMER: \pause
El vector $\vec{y_B}$ en sistema \refsys{A}: \[ \vec{y_B} = -\sin\theta \vec{x_A} +\cos\theta\vec{y_A} =
\begin{bmatrix}\vec{x_A} & \vec{y_A} \end{bmatrix} \begin{bmatrix} -\sin\theta\\\cos\theta \end{bmatrix}\]

#+BEAMER: \pause

 El punto $P$ en sistema \refsys{A}: \[  \vecref{p}{A} = \pref{p_x}{A} \vec{x_A} + \pref{p_x}{A} \vec{y_A} =
 \begin{bmatrix} \vec{x_A} & \vec{y_A} \end{bmatrix} \begin{bmatrix} \pref{p_x}{A}\\ \pref{p_y}{A} \end{bmatrix} \]

#+BEAMER: \pause

So
\[\vecref{p}{A} = t + \vecref{p}{B} = \begin{bmatrix}x\\y\end{bmatrix} + \begin{bmatrix} \vec{x_B} & \vec{y_B} \end{bmatrix} \begin{bmatrix} \pref{p_x}{B}\\ \pref{p_y}{B} \end{bmatrix} =
\begin{bmatrix}x\\y\end{bmatrix} + \begin{bmatrix} \vec{x_A} & \vec{y_A} \end{bmatrix} \begin{bmatrix} \cos\theta & -\sin\theta\\\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} \pref{p_x}{B}\\ \pref{p_y}{B} \end{bmatrix}\]
*** ignore                                                         :noexport:



** Ejemplo
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.6
:END:


#+begin_export latex
\begin{center}
\begin{tikzpicture}[scale=0.5]

\def\xxa{4}
\def\yya{4}
\def\bx{4}
\def\by{2}
\def\thth{30}
\pgfmathsetmacro{\cth}{cos(\thth)}
\pgfmathsetmacro{\sth}{sin(\thth)}
\pgfmathsetmacro{\xxb}{\cth*(\xxa-\bx) + \sth*(\yya-\by)}
\pgfmathsetmacro{\yyb}{-\sth*(\xxa-\bx) + \cth*(\yya-\by)}

\draw[step=1cm, gray, very thin] (-2, -2) grid (12,12);

\refframe{4}{$x_A$}{$y_A$}{blue!80!black}

\begin{scope}[xshift = \bx cm, yshift=\by cm, rotate=\thth]
  \draw[step=1cm, red!40!gray, very thin] (-2, -2) grid (8,8);
  \refframe{4}{$x_B$}{$y_B$}{red!80!black}
  \node[red!80!black, pin={[red!80!black] 30:{($1$, $\sqrt{3}$)}}, circle, fill, inner sep=1pt] at (\xxb cm, \yyb cm) {};
\end{scope}

\draw[->] (7, 2) arc[radius=3cm, start angle=0, end angle=30] node[right, pos=0.5] {$30^\circ$};

%\node[red!80!black, pin=30:{}, circle, fill, inner sep=1pt] at (\xxa cm, \yya cm) {};
\end{tikzpicture}
\end{center}
#+end_export


*** Text
:PROPERTIES:
:BEAMER_col: 0.4
:END:

\small
Determine la matriz de rotación $R_{ab}$ y la translación $t_{ab}$ que definen la transformación entre \refsys{B} y \refsys{A}. Verifique que
\begin{align*}
^Ap &= \begin{bmatrix}4\\4\end{bmatrix} = R_{ab} ^Bp + t_{ab}\\
&=  R_{ab}\begin{bmatrix}1\\\sqrt{3}\end{bmatrix} + t_{ab}
\end{align*}

*** Notes                                                          :noexport:

- Rotación R_ab: columnas son las vectores unitarias de B dado en A:
  - xB = [cos30; sin30] = [sqrt(3)/2; 1/2]
  - yB = [-sin30;cos30] = [-1/2; sqrt(3)/2]
- Traslación del origen de B, dado en A
  - tab = [4;2]
- Calcular el punto ^Ap
  Rab ^B p + t_ab = [c30;s30]*1 + [-s30;c30] sqrt(3) + [4;2]
  = [sqrt(3)/2 - sqrt(3)/2 + 4; 1/2 + sqrt(3)/2*sqrt(3) + 2]
  = [4;4]
** Ejercicio
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.6
:END:


#+begin_export latex
\begin{center}
\begin{tikzpicture}[scale=0.5]

\def\xxa{4}
\def\yya{4}
\def\bx{4}
\def\by{6}
\def\thth{-60}
\pgfmathsetmacro{\cth}{cos(\thth)}
\pgfmathsetmacro{\sth}{sin(\thth)}
\pgfmathsetmacro{\xxb}{\cth*(\xxa-\bx) + \sth*(\yya-\by)}
\pgfmathsetmacro{\yyb}{-\sth*(\xxa-\bx) + \cth*(\yya-\by)}

\draw[step=1cm, gray, very thin] (-2, -2) grid (12,12);

\refframe{4}{$x_A$}{$y_A$}{blue!80!black}

\begin{scope}[xshift = \bx cm, yshift=\by cm, rotate=\thth]
  \draw[step=1cm, red!40!gray, very thin] (-2, -2) grid (8,8);
  \refframe{4}{$x_B$}{$y_B$}{red!80!black}
  \node[red!80!black, pin={[red!80!black] -100:{( $\sqrt{3}$, $-1$)}}, circle, fill, inner sep=1pt] at (\xxb cm, \yyb cm) {};
\end{scope}

\draw[->] (7, 6) arc[radius=3cm, start angle=0, end angle=-60] node[right, pos=0.5] {$-60^\circ$};

%\node[red!80!black, pin=30:{}, circle, fill, inner sep=1pt] at (\xxa cm, \yya cm) {};
\end{tikzpicture}
\end{center}
#+end_export

*** Text
:PROPERTIES:
:BEAMER_col: 0.4
:END:

Determine la matriz de rotación $R_{ab}$ y la translación $t_{ab}$ que definen la transformación entre \refsys{B} y \refsys{A}. Verifique que
\begin{align*}
^Ap &= \begin{bmatrix}4\\4\end{bmatrix} = R_{ab} ^Bp + t_{ab}\\
&=  R_{ab}\begin{bmatrix}\sqrt{3}\\-1\end{bmatrix} + t_{ab}
\end{align*}


** A Programar


* Pose en 3D                                                       :noexport:

** Rotación en 3D

\begin{center}
\includegraphics[height=0.5\textheight]{../figures/MLS-fig2.2.png}

\footnotesize Murray, Li and Sastry \emph{A mathematical introduction to robotic manipulation}
\end{center}

** Mapa exponencial


** Pose en 3D

** Coordenadas homogéneas

